name: Android Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the app
        run: ./gradlew build

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Upload a apk file to Azure Storage Blob using Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.23.0
          inlineScript: |
            az storage blob upload \
                --account-name cliniccallrobo \
                --container-name blob-upload-test \
                --name apk \
                --file app/build/outputs/apk/debug/app-debug.apk \
                --auth-mode login
